# target programming lamguage
language: java

# JDK versios support
jdk:
  - oraclejdk7
  - oraclejdk8

sudo: required

services:
  - postgresql

# run tests, findbugs, pmd and friends using Ant, Maven or Gradle
script: ant test

before_script:
  - psql -c "create database bdvendas;" -U postgres
  - psql -c "alter user postgres with password 'admin'" -U postgres
  - psql -c "create table produto (id_produto integer not null,nome character varying(30),preco real not null,quantidade real not null,descricao character(100));" -U postgres

