/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author cesar.nascimento
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCad_Venda = new javax.swing.JMenuItem();
        jMenuItemCons_Venda = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCad_Prod = new javax.swing.JMenuItem();
        jMenuItemCons_Prod = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemCad_Func = new javax.swing.JMenuItem();
        jMenuItemCons_Func = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemCad_Clien = new javax.swing.JMenuItem();
        jMenuItemCons_Client = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jMenu1.setText("Vendas");

        jMenuItemCad_Venda.setText("Cadastro");
        jMenuItemCad_Venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCad_VendaMousePressed(evt);
            }
        });
        jMenu1.add(jMenuItemCad_Venda);

        jMenuItemCons_Venda.setText("Consulta");
        jMenuItemCons_Venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCons_VendaMousePressed(evt);
            }
        });
        jMenu1.add(jMenuItemCons_Venda);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produtos");

        jMenuItemCad_Prod.setText("Cadastro");
        jMenuItemCad_Prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCad_ProdMousePressed(evt);
            }
        });
        jMenu2.add(jMenuItemCad_Prod);

        jMenuItemCons_Prod.setText("Consulta");
        jMenuItemCons_Prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCons_ProdMousePressed(evt);
            }
        });
        jMenu2.add(jMenuItemCons_Prod);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Funcionários");

        jMenuItemCad_Func.setText("Cadastro");
        jMenuItemCad_Func.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCad_FuncMousePressed(evt);
            }
        });
        jMenu4.add(jMenuItemCad_Func);

        jMenuItemCons_Func.setText("Consulta");
        jMenuItemCons_Func.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCons_FuncMousePressed(evt);
            }
        });
        jMenu4.add(jMenuItemCons_Func);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Clientes");

        jMenuItemCad_Clien.setText("Cadastro");
        jMenuItemCad_Clien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCad_ClienMousePressed(evt);
            }
        });
        jMenu5.add(jMenuItemCad_Clien);

        jMenuItemCons_Client.setText("Consulta");
        jMenuItemCons_Client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCons_ClientMousePressed(evt);
            }
        });
        jMenu5.add(jMenuItemCons_Client);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCad_ProdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCad_ProdMousePressed
        Cad_Produ cf = new Cad_Produ();
        cf.setVisible(true);
    }//GEN-LAST:event_jMenuItemCad_ProdMousePressed

    private void jMenuItemCad_FuncMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCad_FuncMousePressed
        Cad_Func cf = new Cad_Func();
        cf.setVisible(true);
    }//GEN-LAST:event_jMenuItemCad_FuncMousePressed

    private void jMenuItemCons_FuncMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCons_FuncMousePressed
        Cons_Func cf = new Cons_Func();
        cf.setVisible(true);
    }//GEN-LAST:event_jMenuItemCons_FuncMousePressed

    private void jMenuItemCad_ClienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCad_ClienMousePressed
        Cad_Clien cc = new Cad_Clien();
        cc.setVisible(true);
    }//GEN-LAST:event_jMenuItemCad_ClienMousePressed

    private void jMenuItemCad_VendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCad_VendaMousePressed
        Cad_Venda cv = new Cad_Venda();
        cv.setVisible(true);
    }//GEN-LAST:event_jMenuItemCad_VendaMousePressed

    private void jMenuItemCons_VendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCons_VendaMousePressed
        Cons_Venda cv = new Cons_Venda();
        cv.setVisible(true);
    }//GEN-LAST:event_jMenuItemCons_VendaMousePressed

    private void jMenuItemCons_ProdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCons_ProdMousePressed
        Cons_Produ cp = new Cons_Produ();
        cp.setVisible(true);
    }//GEN-LAST:event_jMenuItemCons_ProdMousePressed

    private void jMenuItemCons_ClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCons_ClientMousePressed
        Cons_Clien cc = new Cons_Clien();
        cc.setVisible(true);
    }//GEN-LAST:event_jMenuItemCons_ClientMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCad_Clien;
    private javax.swing.JMenuItem jMenuItemCad_Func;
    private javax.swing.JMenuItem jMenuItemCad_Prod;
    private javax.swing.JMenuItem jMenuItemCad_Venda;
    private javax.swing.JMenuItem jMenuItemCons_Client;
    private javax.swing.JMenuItem jMenuItemCons_Func;
    private javax.swing.JMenuItem jMenuItemCons_Prod;
    private javax.swing.JMenuItem jMenuItemCons_Venda;
    // End of variables declaration//GEN-END:variables
}
