/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Event;
import java.awt.event.MouseEvent;
import javax.swing.JInternalFrame;

/**
 *
 * @author cesar.nascimento
 */
public class Menu extends javax.swing.JFrame {
    
    Cad_Venda cav = new Cad_Venda();
    Cons_Venda cov = new Cons_Venda();
    Cad_Produ cap = new Cad_Produ();
    Cons_Produ cop = new Cons_Produ();
    Cad_Func caf = new Cad_Func();
    Cons_Func cof = new Cons_Func();
    Cad_Clien cac = new Cad_Clien();
    Cons_Clien coc = new Cons_Clien();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCad_Venda = new javax.swing.JMenuItem();
        jMenuItemCons_Venda = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCad_Prod = new javax.swing.JMenuItem();
        jMenuItemCons_Prod = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemCad_Func = new javax.swing.JMenuItem();
        jMenuItemCons_Func = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemCad_Clien = new javax.swing.JMenuItem();
        jMenuItemCons_Client = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        jMenu1.setText("Vendas");

        jMenuItemCad_Venda.setText("Cadastro");
        jMenuItemCad_Venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCad_VendaMousePressed(evt);
            }
        });
        jMenu1.add(jMenuItemCad_Venda);

        jMenuItemCons_Venda.setText("Consulta");
        jMenuItemCons_Venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCons_VendaMousePressed(evt);
            }
        });
        jMenu1.add(jMenuItemCons_Venda);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produtos");

        jMenuItemCad_Prod.setText("Cadastro");
        jMenuItemCad_Prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCad_ProdMousePressed(evt);
            }
        });
        jMenu2.add(jMenuItemCad_Prod);

        jMenuItemCons_Prod.setText("Consulta");
        jMenuItemCons_Prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCons_ProdMousePressed(evt);
            }
        });
        jMenu2.add(jMenuItemCons_Prod);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Funcionários");

        jMenuItemCad_Func.setText("Cadastro");
        jMenuItemCad_Func.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCad_FuncMousePressed(evt);
            }
        });
        jMenu4.add(jMenuItemCad_Func);

        jMenuItemCons_Func.setText("Consulta");
        jMenuItemCons_Func.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCons_FuncMousePressed(evt);
            }
        });
        jMenu4.add(jMenuItemCons_Func);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Clientes");

        jMenuItemCad_Clien.setText("Cadastro");
        jMenuItemCad_Clien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCad_ClienMousePressed(evt);
            }
        });
        jMenu5.add(jMenuItemCad_Clien);

        jMenuItemCons_Client.setText("Consulta");
        jMenuItemCons_Client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCons_ClientMousePressed(evt);
            }
        });
        jMenu5.add(jMenuItemCons_Client);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCad_ProdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCad_ProdMousePressed
        VerificaTelaVisivel(evt);
        jPanel.add(cap);
        cap.setVisible(true);
    }//GEN-LAST:event_jMenuItemCad_ProdMousePressed

    private void jMenuItemCad_FuncMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCad_FuncMousePressed
        VerificaTelaVisivel(evt);
        jPanel.add(caf);
        caf.setVisible(true);
    }//GEN-LAST:event_jMenuItemCad_FuncMousePressed

    private void jMenuItemCons_FuncMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCons_FuncMousePressed
        VerificaTelaVisivel(evt);
        jPanel.add(cof);
        cof.setVisible(true);
    }//GEN-LAST:event_jMenuItemCons_FuncMousePressed

    private void jMenuItemCad_ClienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCad_ClienMousePressed
        VerificaTelaVisivel(evt);
        jPanel.add(cac);
        cac.setVisible(true);
    }//GEN-LAST:event_jMenuItemCad_ClienMousePressed

    private void jMenuItemCad_VendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCad_VendaMousePressed
        VerificaTelaVisivel(evt);
        jPanel.add(cav);
        cav.setVisible(true);
    }//GEN-LAST:event_jMenuItemCad_VendaMousePressed

    private void jMenuItemCons_VendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCons_VendaMousePressed
        VerificaTelaVisivel(evt);
        jPanel.add(cov);
        cov.setVisible(true);
    }//GEN-LAST:event_jMenuItemCons_VendaMousePressed

    private void jMenuItemCons_ProdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCons_ProdMousePressed
        VerificaTelaVisivel(evt);
        jPanel.add(cop);
        cop.setVisible(true);
    }//GEN-LAST:event_jMenuItemCons_ProdMousePressed

    private void jMenuItemCons_ClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCons_ClientMousePressed
        VerificaTelaVisivel(evt);
        jPanel.add(coc);
        coc.setVisible(true);
    }//GEN-LAST:event_jMenuItemCons_ClientMousePressed
    void VerificaTelaVisivel(MouseEvent evt){
        if(evt.getSource()==jMenuItemCad_Venda){
            if(cav.isVisible()){
                //não faz nada
            }else if(cov.isVisible()){
                cov.dispose();
            }else if(cap.isVisible()){
                cap.dispose();
            }else if(cop.isVisible()){
                cop.dispose();
            }else if(caf.isVisible()){
                caf.dispose();
            }else if(cof.isVisible()){
                cof.dispose();
            }else if(cac.isVisible()){
                cac.dispose();
            }else if(coc.isVisible()){
                coc.dispose();
            }     
        }
        if(evt.getSource()==jMenuItemCons_Venda){
            if(cov.isVisible()){
                //não faz nada
            }else if(cav.isVisible()){
                cav.dispose();
            }else if(cap.isVisible()){
                cap.dispose();
            }else if(cop.isVisible()){
                cop.dispose();
            }else if(caf.isVisible()){
                caf.dispose();
            }else if(cof.isVisible()){
                cof.dispose();
            }else if(cac.isVisible()){
                cac.dispose();
            }else if(coc.isVisible()){
                coc.dispose();
            }     
        }
        if(evt.getSource()==jMenuItemCad_Prod){
            if(cap.isVisible()){
                //não faz nada
            }else if(cov.isVisible()){
                cov.dispose();
            }else if(cav.isVisible()){
                cav.dispose();
            }else if(cop.isVisible()){
                cop.dispose();
            }else if(caf.isVisible()){
                caf.dispose();
            }else if(cof.isVisible()){
                cof.dispose();
            }else if(cac.isVisible()){
                cac.dispose();
            }else if(coc.isVisible()){
                coc.dispose();
            }     
        }
        if(evt.getSource()==jMenuItemCons_Prod){
            if(cop.isVisible()){
                //não faz nada
            }else if(cov.isVisible()){
                cov.dispose();
            }else if(cap.isVisible()){
                cap.dispose();
            }else if(cav.isVisible()){
                cav.dispose();
            }else if(caf.isVisible()){
                caf.dispose();
            }else if(cof.isVisible()){
                cof.dispose();
            }else if(cac.isVisible()){
                cac.dispose();
            }else if(coc.isVisible()){
                coc.dispose();
            }     
        }
        if(evt.getSource()==jMenuItemCad_Func){
            if(caf.isVisible()){
                //não faz nada
            }else if(cov.isVisible()){
                cov.dispose();
            }else if(cap.isVisible()){
                cap.dispose();
            }else if(cop.isVisible()){
                cop.dispose();
            }else if(cav.isVisible()){
                cav.dispose();
            }else if(cof.isVisible()){
                cof.dispose();
            }else if(cac.isVisible()){
                cac.dispose();
            }else if(coc.isVisible()){
                coc.dispose();
            }     
        }
        if(evt.getSource()==jMenuItemCons_Func){
            if(cof.isVisible()){
                //não faz nada
            }else if(cov.isVisible()){
                cov.dispose();
            }else if(cap.isVisible()){
                cap.dispose();
            }else if(cop.isVisible()){
                cop.dispose();
            }else if(caf.isVisible()){
                caf.dispose();
            }else if(cav.isVisible()){
                cav.dispose();
            }else if(cac.isVisible()){
                cac.dispose();
            }else if(coc.isVisible()){
                coc.dispose();
            }     
        }
        if(evt.getSource()==jMenuItemCad_Clien){
            if(cac.isVisible()){
                //não faz nada
            }else if(cov.isVisible()){
                cov.dispose();
            }else if(cap.isVisible()){
                cap.dispose();
            }else if(cop.isVisible()){
                cop.dispose();
            }else if(caf.isVisible()){
                caf.dispose();
            }else if(cof.isVisible()){
                cof.dispose();
            }else if(cav.isVisible()){
                cav.dispose();
            }else if(coc.isVisible()){
                coc.dispose();
            }     
        }
        if(evt.getSource()==jMenuItemCons_Client){
            if(coc.isVisible()){
                //não faz nada
            }else if(cov.isVisible()){
                cov.dispose();
            }else if(cap.isVisible()){
                cap.dispose();
            }else if(cop.isVisible()){
                cop.dispose();
            }else if(caf.isVisible()){
                caf.dispose();
            }else if(cof.isVisible()){
                cof.dispose();
            }else if(cac.isVisible()){
                cac.dispose();
            }else if(cav.isVisible()){
                cav.dispose();
            }     
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCad_Clien;
    private javax.swing.JMenuItem jMenuItemCad_Func;
    private javax.swing.JMenuItem jMenuItemCad_Prod;
    private javax.swing.JMenuItem jMenuItemCad_Venda;
    private javax.swing.JMenuItem jMenuItemCons_Client;
    private javax.swing.JMenuItem jMenuItemCons_Func;
    private javax.swing.JMenuItem jMenuItemCons_Prod;
    private javax.swing.JMenuItem jMenuItemCons_Venda;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
